# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

In [12]:
import numpy as np

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [13]:
with open('minutes_n_ingredients.csv', 'r') as file:
    info = file.read()

info = np.loadtxt('minutes_n_ingredients.csv', delimiter=",", skiprows=1, dtype=np.int32)
print(info[0:5, :])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [14]:
column2_maximum = np.max(info[:,1])
column3_max = np.max(info[:,2])


print(f'Максимальное значение второй колонки: {column2_maximum}')
print(f'Максимальное значение третьей колонки: {column3_max}')


column2_srednee = np.mean(info[:,1])
column3_srednee = np.mean(info[:,2])

print(f'Среднее значение второй колонки: {column2_srednee}')
print(f'Среднее значение третьей колонки: {column3_srednee}')


column2_min = np.min(info[:,1])
column3_min = np.min(info[:,2])
print(f'Минимальное значение второй колонки: {column2_min}')
print(f'Минимальное значение третьей колонки: {column3_min}')

column2_mediana = np.median(info[:,1])
column3_mediana = np.median(info[:,2])

print(f'Медиана второй колонки: {column2_mediana}')
print(f'Медиана третьей колонки: {column3_mediana}')


Максимальное значение второй колонки: 2147483647
Максимальное значение третьей колонки: 39
Среднее значение второй колонки: 21601.00169
Среднее значение третьей колонки: 9.05528
Минимальное значение второй колонки: 0
Минимальное значение третьей колонки: 1
Медиана второй колонки: 40.0
Медиана третьей колонки: 9.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

1. найти рецепты (id то есть первый столбик) для которых значение второго столбика равно 0
2. заменить значение второго ст на 1

In [15]:
print(np.count_nonzero(info[:,1] == 0))
info[info == 0] = 1

479


In [16]:
info3 = info[info[:,1] <= np.quantile(info[:,1], 0.75)]
print(info3)

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [ 43407     35      7]
 [498432     65     15]
 [370915      5      4]]


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [17]:
print(len(np.unique(info[:,0])))

100000


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [18]:
print(f'Кол-во различных значений ингредиентов: {len(np.unique(info[:,2]))}')
print(np.unique(info[:,2]))

Кол-во различных значений ингредиентов: 37
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [19]:
info7 = info[info[:,2] <= 5]
print(info7)

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [20]:
info8 = info[:, 2] / info[:, 1]
print(f'Максимальное: {np.max(info8)}\n{info8}')

Максимальное: 24.0
[0.26666667 0.28       0.6        ... 0.23076923 0.8        0.1       ]


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [21]:
info9 = info[np.argsort(info[:, 1])][-100:, 2]
print(np.mean(info9))

6.61


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [22]:
print(info[np.random.randint(info.shape[0], size = 10)])

[[ 68088     30      9]
 [  8875      5      3]
 [162598     30      8]
 [ 40509      5      5]
 [104636     25      5]
 [137951     10      5]
 [228442    500      9]
 [ 24907     75      8]
 [ 30554     10      9]
 [114962     60     15]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [23]:
result = (info[info[:, 2] < np.mean(info[:, 2])].shape[0] / info.shape[0]) * 100
print(result)

58.802


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [24]:
bool_value = (info[:, 1] <= 20) & (info[:, 2] <= 5)
info12 = np.hstack((info, bool_value[:, np.newaxis]))
print(info12)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993    140     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [25]:
print(info12[info12[:, 3] == 1].shape[0]/ info.shape[0] * 100)

9.552


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [26]:
short = info[info[:,1] < 10]
average = info[(info[:,1] >= 10) & (info[:,1] < 20)]
long = info[info[:,1] < 20]

a = min(short.shape[0], average.shape[0], long.shape[0])
rezul = np.array([short[:a], average[:a], long[:a]])
print(rezul)

[[[ 67660      5      6]
  [366174      7      9]
  [204134      5      3]
  ...
  [420725      5      3]
  [  4747      1      9]
  [370915      5      4]]

 [[ 94746     10      6]
  [ 33941     18      9]
  [446597     15      5]
  ...
  [  9831     15      7]
  [335859     12     14]
  [256812     10      3]]

 [[ 94746     10      6]
  [ 67660      5      6]
  [ 33941     18      9]
  ...
  [312448     13      8]
  [252749      5      5]
  [224369      5     15]]]
